import type { Metadata } from "next"
import StyledComponentsRegistry from "@/lib/StyledRegistry"
import { GlobalStyle } from "@/styles/GlobalStyle"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ko">
            <body>
                <StyledComponentsRegistry>
                    <GlobalStyle />
                    {children}
                </StyledComponentsRegistry>
            </body>
        </html>
    )
}
