import type { Metadata } from "next"
import localFont from "next/font/local"
import StyledComponentsRegistry from "@/lib/StyledRegistry"
import { GlobalStyle } from "@/styles/GlobalStyle"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

const pretendard = localFont({
    src: "../../public/fonts/PretendardVariable.ttf"
})

export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ko">
            <body className={pretendard.className}>
                <StyledComponentsRegistry>
                    <GlobalStyle />
                    {children}
                </StyledComponentsRegistry>
            </body>
        </html>
    )
}
